/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package scientificcalculator;
import Calculator.Utils.Input;
import Calculator.Calculator;

/**
 *
 * @author pcmn
 */
public class ScientificCalculator extends javax.swing.JFrame {

    public Input input;
    public Calculator calculator = new Calculator();
    public String answer = "";

    /**
     * Creates new form NewJFrame
     */
    public ScientificCalculator() {
        initComponents();
        this.input = new Input(this.InputField);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        log = new javax.swing.JButton();
        LnButton = new javax.swing.JButton();
        LParan = new javax.swing.JButton();
        RParan = new javax.swing.JButton();
        SquareButton = new javax.swing.JButton();
        FiveButton = new javax.swing.JButton();
        FourButton = new javax.swing.JButton();
        SixButton = new javax.swing.JButton();
        MultiplyButton = new javax.swing.JButton();
        DivideButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        SubtractButton = new javax.swing.JButton();
        ThreeButton = new javax.swing.JButton();
        TwoButton = new javax.swing.JButton();
        OneButton = new javax.swing.JButton();
        ZeroButton = new javax.swing.JButton();
        DecimalButton = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        AnswerButton = new javax.swing.JButton();
        EqualButton = new javax.swing.JButton();
        SevenButton = new javax.swing.JButton();
        EightButton = new javax.swing.JButton();
        NineButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        AllClearButton = new javax.swing.JButton();
        ExponentButton = new javax.swing.JButton();
        SinButton = new javax.swing.JButton();
        FactorialButton = new javax.swing.JButton();
        TanButton = new javax.swing.JButton();
        CosButton = new javax.swing.JButton();
        OutputField = new javax.swing.JTextField();
        InputField = new javax.swing.JTextField();
        ExponentButton1 = new javax.swing.JButton();
        SinInverseButton = new javax.swing.JButton();
        CosInverseButton = new javax.swing.JButton();
        TanInverseButton = new javax.swing.JButton();
        SquareRootButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        log.setText("log");
        log.setMargin(new java.awt.Insets(0, 0, 0, 0));
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        LnButton.setText("ln");
        LnButton.setActionCommand("8");
        LnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnButtonActionPerformed(evt);
            }
        });

        LParan.setText("(");
        LParan.setToolTipText("");
        LParan.setActionCommand("9");
        LParan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LParanActionPerformed(evt);
            }
        });

        RParan.setText(")");
        RParan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RParanActionPerformed(evt);
            }
        });

        SquareButton.setText("<html>x<sup>2</sup></html>");
        SquareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquareButtonActionPerformed(evt);
            }
        });

        FiveButton.setText("5");
        FiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveButtonActionPerformed(evt);
            }
        });

        FourButton.setText("4");
        FourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourButtonActionPerformed(evt);
            }
        });

        SixButton.setText("6");
        SixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixButtonActionPerformed(evt);
            }
        });

        MultiplyButton.setText("*");
        MultiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplyButtonActionPerformed(evt);
            }
        });

        DivideButton.setText("/");
        DivideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivideButtonActionPerformed(evt);
            }
        });

        AddButton.setText("+");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        SubtractButton.setText("-");
        SubtractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtractButtonActionPerformed(evt);
            }
        });

        ThreeButton.setText("3");
        ThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeButtonActionPerformed(evt);
            }
        });

        TwoButton.setText("2");
        TwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoButtonActionPerformed(evt);
            }
        });

        OneButton.setText("1");
        OneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneButtonActionPerformed(evt);
            }
        });

        ZeroButton.setText("0");
        ZeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroButtonActionPerformed(evt);
            }
        });

        DecimalButton.setText(".");
        DecimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecimalButtonActionPerformed(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jButton18.setText("<html>x<sup>10</sup></html>");
        jButton18.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        AnswerButton.setText("Ans");
        AnswerButton.setMargin(new java.awt.Insets(2, 10, 2, 10));
        AnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerButtonActionPerformed(evt);
            }
        });

        EqualButton.setText("=");
        EqualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualButtonActionPerformed(evt);
            }
        });

        SevenButton.setText("7");
        SevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenButtonActionPerformed(evt);
            }
        });

        EightButton.setText("8");
        EightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightButtonActionPerformed(evt);
            }
        });

        NineButton.setText("9");
        NineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("DEL");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        AllClearButton.setText("AC");
        AllClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllClearButtonActionPerformed(evt);
            }
        });

        ExponentButton.setText("^");
        ExponentButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ExponentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExponentButtonActionPerformed(evt);
            }
        });

        SinButton.setText("sin");
        SinButton.setActionCommand("8");
        SinButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        SinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinButtonActionPerformed(evt);
            }
        });

        FactorialButton.setText("x!");
        FactorialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FactorialButtonActionPerformed(evt);
            }
        });

        TanButton.setText("tan");
        TanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanButtonActionPerformed(evt);
            }
        });

        CosButton.setText("cos");
        CosButton.setToolTipText("");
        CosButton.setActionCommand("9");
        CosButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        CosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosButtonActionPerformed(evt);
            }
        });

        OutputField.setEditable(false);
        OutputField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        OutputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutputFieldActionPerformed(evt);
            }
        });

        InputField.setEditable(false);
        InputField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ExponentButton1.setText("^");
        ExponentButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ExponentButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExponentButton1ActionPerformed(evt);
            }
        });

        SinInverseButton.setText("<html>sin<sup>1</sup></html>");
        SinInverseButton.setActionCommand("8");
        SinInverseButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        SinInverseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinInverseButtonActionPerformed(evt);
            }
        });

        CosInverseButton.setText("<html>cos<sup>1</sup></html>");
        CosInverseButton.setToolTipText("");
        CosInverseButton.setActionCommand("9");
        CosInverseButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        CosInverseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosInverseButtonActionPerformed(evt);
            }
        });

        TanInverseButton.setText("<html>tan<sup>1</sup></html>");
        TanInverseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanInverseButtonActionPerformed(evt);
            }
        });

        SquareRootButton.setText("<html>&radic;</html>");
        SquareRootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquareRootButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(ExponentButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ExponentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(SinInverseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DecimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(CosInverseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LParan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(TanInverseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RParan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MultiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnswerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(SquareRootButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FactorialButton)
                            .addComponent(SquareButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AllClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DivideButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SubtractButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EqualButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(OutputField))
                .addGap(12, 12, 12))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(InputField)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(OutputField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TanInverseButton)
                    .addComponent(SquareRootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SinInverseButton)
                    .addComponent(ExponentButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CosInverseButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FactorialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExponentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CosButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(RParan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LParan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SquareButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(AllClearButton)
                    .addComponent(DeleteButton)
                    .addComponent(NineButton)
                    .addComponent(EightButton)
                    .addComponent(SevenButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(DivideButton)
                    .addComponent(MultiplyButton)
                    .addComponent(SixButton)
                    .addComponent(FiveButton)
                    .addComponent(FourButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(SubtractButton)
                    .addComponent(AddButton)
                    .addComponent(ThreeButton)
                    .addComponent(TwoButton)
                    .addComponent(OneButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(EqualButton)
                    .addComponent(AnswerButton)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DecimalButton)
                    .addComponent(ZeroButton))
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(InputField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(416, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    private void logActionPerformed(java.awt.event.ActionEvent evt) {                                    
        this.input.addFunction(" log ( ");
    }                                   

    private void LnButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.input.addFunction(" ln ( ");
    }                                        

    private void LParanActionPerformed(java.awt.event.ActionEvent evt) {                                       
        this.input.addToken(" ( ");
    }                                      

    private void RParanActionPerformed(java.awt.event.ActionEvent evt) {                                       
        this.input.addToken(" ) ");
    }                                      

    private void SquareButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        this.input.addFunction(" sqr ( ");
    }                                            

    private void FiveButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        this.input.addNumber("5");
    }                                          

    private void FourButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        this.input.addNumber("4");
    }                                          

    private void SixButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.input.addNumber("6");
    }                                         

    private void MultiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        this.input.addToken(" * ");
    }                                              

    private void DivideButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        this.input.addToken(" / ");
    }                                            

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.input.addToken(" + ");
    }                                         

    private void SubtractButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        this.input.addToken(" - ");
    }                                              

    private void ThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            

        this.input.addNumber("3");
    }                                           

    private void TwoButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.input.addNumber("2");
    }                                         

    private void OneButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.input.addNumber("1");
    }                                         

    private void ZeroButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        this.input.addNumber("0");
    }                                          

    private void DecimalButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        this.input.addToken(".");
    }                                             

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void AnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        this.input.addToken(this.answer);
    }                                            

    private void EqualButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        String output = this.calculator.calculate(this.calculator.parse(this.input.toString()));
        this.OutputField.setText(output);
        this.answer = output;
        this.input.clearStack();
    }                                           

    private void SevenButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        this.input.addNumber("7");
    }                                           

    private void EightButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        this.input.addNumber("8");
    }                                           

    private void NineButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        this.input.addNumber("9");
    }                                          

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        this.input.removeToken();
    }                                            

    private void AllClearButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        this.input.clearStack();
    }                                              

    private void ExponentButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        this.input.addToken(" ^ ");
    }                                              

    private void SinButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.input.addFunction(" sin ( ");
    }                                         

    private void FactorialButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        this.input.addFunction(" fact ( ");
    }                                               

    private void TanButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.input.addFunction(" tan ( ");
    }                                         

    private void CosButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.input.addFunction(" cos ( ");
    }                                         

    private void OutputFieldActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void ExponentButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void SinInverseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.input.addFunction(" sinInv ( ");
    }                                                

    private void CosInverseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.input.addFunction(" cosInv ( ");    }                                                

    private void TanInverseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.input.addFunction(" tanInv ( ");
    }                                                

    private void SquareRootButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.input.addFunction(" sqrt ( ");
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScientificCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton AddButton;
    private javax.swing.JButton AllClearButton;
    private javax.swing.JButton AnswerButton;
    private javax.swing.JButton CosButton;
    private javax.swing.JButton CosInverseButton;
    private javax.swing.JButton DecimalButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton DivideButton;
    private javax.swing.JButton EightButton;
    private javax.swing.JButton EqualButton;
    private javax.swing.JButton ExponentButton;
    private javax.swing.JButton ExponentButton1;
    private javax.swing.JButton FactorialButton;
    private javax.swing.JButton FiveButton;
    private javax.swing.JButton FourButton;
    private javax.swing.JTextField InputField;
    private javax.swing.JButton LParan;
    private javax.swing.JButton LnButton;
    private javax.swing.JButton MultiplyButton;
    private javax.swing.JButton NineButton;
    private javax.swing.JButton OneButton;
    private javax.swing.JTextField OutputField;
    private javax.swing.JButton RParan;
    private javax.swing.JButton SevenButton;
    private javax.swing.JButton SinButton;
    private javax.swing.JButton SinInverseButton;
    private javax.swing.JButton SixButton;
    private javax.swing.JButton SquareButton;
    private javax.swing.JButton SquareRootButton;
    private javax.swing.JButton SubtractButton;
    private javax.swing.JButton TanButton;
    private javax.swing.JButton TanInverseButton;
    private javax.swing.JButton ThreeButton;
    private javax.swing.JButton TwoButton;
    private javax.swing.JButton ZeroButton;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton log;
    // End of variables declaration                   
}
